lojaHemilly/Models/Venda.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace lojaHemilly.Models
{
    public class Venda
    {
        public int Id { get; set; }
        public DateTime DataDaVenda { get; set; }
        public int ClienteId { get; set; }
        public int NumeroParcelas { get; set; }
        public Cliente Cliente { get; set; }
        public decimal Total { get; set; }
        

        /// <summary>
        /// Caso o cliente dê algum valor de entrada na compra para abater na criaçao 
        /// das parcelas.
        /// </summary>
        public decimal Entrada { get; set; }


        /// <summary>
        /// 1 - PARCELADO
        /// 2 - A VISTA
        /// </summary>
        public int TipoPagamento { get; set; }

        /// <summary>
        /// Verifica se a venda esta paga ou não
        /// 0-> Compra ainda não paga
        /// 1-> Compra toda paga, todas as parcelas foram pagas
        /// </summary>
        public int Status { get; set; }
        public ICollection<ItemVenda> Itens { get; set; }
        public ICollection<Parcela> Parcelas { get; set; }
    }
}

lojaHemilly/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lojaHemilly.DataBase;
using lojaHemilly.Models;
using lojaHemilly.Service;
using MySqlConnector;
using System.Data.SqlClient;

namespace lojaHemilly.Controllers
{
    public class VendasController : Controller
    {
        private readonly FlorDeLizContext _context;
        private readonly IVendaService _vendaService;
        private readonly IItemVendaService _itemVendaService;
        private readonly IParcelaService _parcelaService;

        public VendasController(
            FlorDeLizContext context,
            IVendaService vendaService,
            IItemVendaService itemVendaService,
            IParcelaService parcelaService)
        {
            _context = context;
            _vendaService = vendaService;
            _itemVendaService = itemVendaService;
            _parcelaService = parcelaService;
        }

        public IActionResult Create()
        {

            //select Item
            ViewData["ClienteId"] = ListaClientesSelectItem();
            return View();
        }

        private IEnumerable<SelectListItem> ListaClientesSelectItem()
        {
            var listaManual = new List<SelectListItem>
            {
                new SelectListItem { Text = "SELECIONE UM CLIENTE ", Value = "" }
            };

            // Criando a lista selecionável a partir dos clientes
            var listaSelecionavelClientes = new SelectList(_context.Clientes.Where(a => a.Status == 1), "ClienteID", "Nome");

            // Concatenando a lista manual com a lista selecionável dos clientes
            var listaCompleta = listaManual.Concat(listaSelecionavelClientes);

            return listaCompleta;
        }


        [HttpPost]
        public async Task<Mensagem> SalvarVendaAsync(VendaViewModel venda)
        {
            var m = new Mensagem();
            try
            {
                decimal entrada = decimal.Parse(venda.Entrada.Replace("R$", "").Trim());
                decimal total = Convert.ToDecimal(venda.Total.Replace("R$", "").Trim());

                var novaVenda = new Venda();
                novaVenda.Entrada = entrada;
                novaVenda.Total = total;
                novaVenda.DataDaVenda = Convert.ToDateTime(venda.DataDaVenda);
                novaVenda.ClienteId = venda.ClienteId;
                novaVenda.TipoPagamento = venda.TipoFormaPagamento;

                //venda a vista;
                if (venda.TipoFormaPagamento == 2)
                {
                    novaVenda.NumeroParcelas = 0;
                    novaVenda.Status = 1;
                }
                else
                {
                    novaVenda.NumeroParcelas = venda.NumeroParcelas;
                    novaVenda.Status = 0;
                }

                var vendaIncluida = await _vendaService.Create(novaVenda);

                if (vendaIncluida.Id != 0)
                {
                    await SalvarItensVendaAsync(vendaIncluida.Id, venda.ItensVenda);

                    //Criando parcelas
                    if (venda.TipoFormaPagamento == 1)
                        await SalvarParcelasAsync(vendaIncluida);
                }
                m.Status = 1;
                m.Descricao = "Compra incluída com sucesso";
                return m;
            }
            catch (Exception ex)
            {
                m.Status = 0;
                m.Descricao = ex.Message.ToString();
                return m;
            }
        }

        private async Task<Mensagem> SalvarItensVendaAsync(int idVenda, IEnumerable<ItemVendaDto> itens)
        {
            Mensagem m = new Mensagem();
            try
            {
                foreach (var item in itens)
                {
                    var novoItem = new ItemVenda();
                    novoItem.NomeDoProduto = item.NomeDoProduto.ToUpper();
                    novoItem.VendaId = idVenda;
                    novoItem.PrecoUnitario = Convert.ToDecimal(item.PrecoUnitario.Replace(".", ","));
                    novoItem.Quantidade = item.Quantidade;
                    await _itemVendaService.Create(novoItem);
                }

                m.Status = 1;
            }
            catch (Exception ex)
            {
                m.Status = 0;
                m.Descricao = ex.Message;
                return m;
            }

            return m;
        }

        private async Task<bool> SalvarParcelasAsync(Venda venda)
        {
            var valorParcela = (venda.Total - venda.Entrada) / venda.NumeroParcelas;

            try
            {
                for (var i = 1; i <= venda.NumeroParcelas; i++)
                {
                    var dataVenda = venda.DataDaVenda;
                    var parcela = new Parcela();
                    parcela.VendaId = venda.Id;
                    parcela.NumeroParcela = i;
                    parcela.DataVencimento = dataVenda.AddMonths(i);
                    parcela.Valor = valorParcela;
                    parcela.Pago = false;
                    await _parcelaService.Create(parcela);
                }
            }
            catch (Exception ex)
            {
                return false;
            }

            return true;
        }

        #region METODOS DEFAULT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DataDaVenda,ClienteId,PrecoTotal,NumeroParcelas,Total")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteID", "Nome", venda.ClienteId);
            return View(venda);
        }



        public async Task<IActionResult> Index(DateTime? startDate, DateTime? endDate, int? status, int? idCliente)
        {

            if (!status.HasValue)
                status = 0;

            var query = $"";

            if (status == -1)
            {
                query = $"(status = 0 or status = 1) ";
            }
            else
            {
                query = $"(status = {status}) ";
            }

            if (startDate != null)
            {
                string de = String.Format("{0:yyyy-MM-dd}", Convert.ToDateTime(startDate));
                query += $" and (date(DataDaVenda) >= '{de}') ";
            }

            if (endDate != null)
            {
                string ate = String.Format("{0:yyyy-MM-dd}", Convert.ToDateTime(endDate));
                query += $"and (date(DataDaVenda) <= '{ate}') ";
            }

            if (idCliente != null)
            {
                query += $"and ClienteId = {idCliente}";
            }

            var sqlQuery = $"SELECT * FROM vendas where {query}";

            var vendas = await _context.Vendas.FromSqlRaw(sqlQuery).Include(v => v.Cliente).Include(a => a.Parcelas).ToListAsync();

            ViewData["StartDate"] = startDate != null ? startDate.Value.ToString("yyyy-MM-dd") : "";
            ViewData["EndDate"] = endDate != null ? endDate.Value.ToString("yyyy-MM-dd") : "";
            ViewData["status"] = status.ToString();

            ViewData["ListaSeletFiltro"] = ListaSelect();
            ViewData["ClienteId"] = ListaClientesSelectItem();

            return View(vendas);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas.FindAsync(id);
            if (venda == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteID", "Nome", venda.ClienteId);
            return View(venda);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DataDaVenda,ClienteId,PrecoTotal,NumeroParcelas,Total")] Venda venda)
        {
            if (id != venda.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaExists(venda.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteID", "Nome", venda.ClienteId);
            return View(venda);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

lojaHemilly/Views/Vendas/Create.cshtml
@model lojaHemilly.Models.Venda

@{
    ViewData["Title"] = "Create";
}

<style>
    #btnAdicionar {
        margin-top: 22px;
        width: 100%;
    }

    #valorTotal {
        text-align: right;
        font-size: 30px;
        font-weight: bold;
    }

    .vertical-align-middle {
        vertical-align: middle;
    }

</style>


<h1>Nova venda</h1>


<div class="card card-custom gutter-b">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">
                Nova venda
                <small>Insira as informações</small>
            </h3>
        </div>
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-md-12">
                <div class="form-group row">
                    <label class="control-label">Cliente</label>
                    <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.ClienteId"></select>
                </div>
                <div class="form-group row">
                    <label class="control-label">Data Compra</label>
                    <input type="date" id="DataCompra" class="form-control" />
                </div>

                <div class="form-group row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label for="input1">Descrição Produto</label>
                            <input type="text" class="form-control" id="NomeDoProduto">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="input2">Quantidade</label>
                            <input type="number" value="1" class="form-control" id="Quantidade">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="input2">Valor unitário</label>
                            <input type="text" class="form-control" value="0,00"
                                   onkeyup="FormatarMoeda(this);" onkeydown="AdicionarProdutoEnter(event);"
                                   id="PrecoUnitario">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <button type="button" class="btn btn-primary" onclick="AdicionarProduto();" id="btnAdicionar">Adicionar</button>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <button type="button" class="btn btn-primary" onclick="FinalizarCompra();" id="btnAdicionar">Finalizar</button>
                        </div>
                    </div>

                </div>

            </div>
        </div>

        <div id="valorTotal"></div>

    </div>
</div>

<div class="card card-custom gutter-b">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">
                Produtos
                <small> Descrição, valor e quantidade dos produtos da compra </small>
            </h3>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Valor unitário</th>
                        <th scope="col">Quantidade</th>
                        <th scope="col">Total</th>
                        <th scope="col">...</th>
                    </tr>
                </thead>
                <tbody id="tbodyProdutos">
                    @* <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>mdo</td>
                    <td>mdo</td>
                    </tr> *@
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- Modal-->
<div class="modal fade" id="modal_finalizacao" data-backdrop="static" tabindex="-1" backs role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"> Finalização Compra </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>N° Parcela(s):</label>
                                <div class="input-group">
                                    <select id="TipoFormaPagamento" class="form-control" onchange="FormaPagamento();">
                                        <option value="2">A VISTA</option>
                                        <option value="1">PARCELADO</option>
                                    </select>
                                </div>
                                <span class="form-text text-muted">Tipo de pagamento</span>
                            </div>
                            <div class="col-lg-6" style="display:none" id="divEntrada">
                                <label>Entrada:</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="ValorEntrada" value="0,00" onkeyup="FormatarMoeda(this); RefazerValorTotal();">
                                </div>
                                <span class="form-text text-muted">Entrada para abater nas parcelas</span>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group row" id="divNumeroParcelas" style="display:none">
                                <label class="control-label">Número de parcelas: </label>
                                <input type="number" value="1" class="form-control" id="NumeroParcelas" onkeyup="CalcularPrecoParcela()" onchange="CalcularPrecoParcela()">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <h4 style="text-align:center" id="h4TotalCompra"> </h4>
                            </div>
                        </div>

                        <div class="form-group row" id="divTableParcelas" style="display:none">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Nº Parcela</th>
                                        <th scope="col">Data</th>
                                        <th scope="col">Valor</th>
                                    </tr>
                                </thead>
                                <tbody id="tbodyParcelas">
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light-warning font-weight-bold" onclick="LimparDadosModalPagamento();" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success font-weight-bold" onclick="SalvarCompra();">Salvar</button>
            </div>
        </div>
    </div>
</div>





@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script src="/Views/Vendas/Js/Create/Create.js"></script>
        <script src="/Views/Vendas/Js/Create/Validacao.js"></script>
        <script src="/Views/Vendas/Js/Create/Finalizacao.js"></script>
        <script src="/Views/Vendas/Js/Create/Salvar.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/cleave.js@1.6.0/dist/cleave.min.js"></script>
    }
}

lojaHemilly/Views/Vendas/Index.cshtml
@using static lojaHemilly.Controllers.VendasController
@model IEnumerable<lojaHemilly.Models.Venda>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var listaSelect = ViewData["ListaSeletFiltro"] as List<ItensSelectStatus>;
 
    var startDate = ViewData["StartDate"] as string;
    var endDate = ViewData["EndDate"] as string;
    var status = ViewData["status"] as string;
}

<style>
    .btnOpcao{

        height:20px;
        text-align:center;
    }
</style>

<h1>Lista de vendas</h1>

<div class="card card-custom gutter-b">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">
                Filtros Pesquisa
                <small>sub title</small>
            </h3>
        </div>
    </div>
    <div class="card-body">
        <form method="get" asp-controller="Vendas" asp-action="Index">

            <div class="form-group row">
                <div class="col-lg-12">
                <label class="control-label">Cliente</label>
                    <select class="form-control" id="idCliente" name="idCliente" asp-items="ViewBag.ClienteId"></select>
            </div>
            </div>

            <div class="form-group row">
                <div class="col-lg-4">
                    <label>Data Inicio:</label>
                    <input type="date" class="form-control" id="startDate" name="startDate" value="@startDate">
                    <span class="form-text text-muted">Data inicio pesquisa</span>
                </div>
                <div class="col-lg-4">
                    <label>Data fim:</label>
                    <input type="date" class="form-control" id="endDate" name="endDate" value="@endDate">
                    <span class="form-text text-muted">Data fim pesquisa</span>
                </div>
                <div class="col-lg-4">
                    <label>Status:</label>
                    <select id="status" name="status" class="form-control">
                        @foreach (var item in listaSelect)
                        {
                            @if (item.Value.ToString() == status)
                            {
                                <option selected="selected" value="@item.Value"> @item.Descricao </option>
                            }
                            else
                            {
                                <option value="@item.Value"> @item.Descricao </option>
                            }
                        }
                    </select>
                    <span class="form-text text-muted">Please enter your username</span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-4">
                    <button class="btn btn-success btn-shadow font-weight-bold mr-2" type="submit">Filtrar</button>
                </div>
            </div>

        </form>
    </div>
</div>

<div class="card card-custom gutter-b">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">
                Vendas
                <small>Lista de vendas</small>
            </h3>
        </div>
    </div>
    <div class="card-body">
        <p>
            <a asp-action="Create">Nova venda</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th> Protocolo </th>
                    <th> Data da compra</th>
                    <th>
                        N° de parcelas
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cliente)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Total)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Entrada)
                    </th>
                    <th>
                        Tipo Pagamento
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                       
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Id
                        </td> <td>
                            @item.DataDaVenda.Date.ToShortDateString()
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumeroParcelas)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cliente.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Total)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Entrada)
                        </td>
                        <td>
                            @if (item.TipoPagamento == 1)
                            {
                                <p>Parcelado</p>
                            }
                            else
                            {
                                <p>A vista</p>
                            }
                        </td>
                        <td>
                            @if (item.Status == 1)
                            {
                                <span class="label label-md label-success label-inline mr-2">Pago</span>
                            }
                            else
                            {
                                <span class="label label-md label-danger label-inline mr-2">Pendente</span>
                            }
                        </td>

                        <td>
                            <a > <span class="label label-md label-success label-inline mr-2">Itens</span></a>
                            @if (item.TipoPagamento == 1)
                            {
                                <a asp-controller="Parcelas" asp-action="Index" asp-route-id="@item.Id"> <span class="label label-md label-warning label-inline mr-2">Parcelas</span></a>
                            }
                          
                        </td>

                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script src="/Views/Vendas/Js/Index/Index.js"></script>
    }
}